# Generated by Django 4.1.5 on 2023-04-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0008_delete_roledelegado'),
        ('custom_profiles', '0002_userprofile_role2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role2',
            field=models.ManyToManyField(blank=True, default='1', to='reuniones.role'),
        ),
    ]
