# Generated by Django 4.0 on 2023-02-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profiles', '0002_rename_user_customuser_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
