# Generated by Django 4.1.5 on 2023-04-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profiles', '0003_remove_userprofile_role2_userprofile_role2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
