# Generated by Django 4.1.5 on 2023-08-12 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profiles', '0004_remove_role_group_alter_role_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='callable_roles',
        ),
    ]
