# Generated by Django 4.1.5 on 2023-04-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profiles', '0004_remove_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='role2',
            new_name='role',
        ),
    ]
