# Generated by Django 4.0 on 2023-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profiles', '0006_userprofile_show_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='groups',
            field=models.ManyToManyField(to='custom_profiles.Group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='group',
            field=models.ManyToManyField(to='custom_profiles.Group'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='custom_profiles.Permission'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(blank=True, to='custom_profiles.Role'),
        ),
    ]
