# Generated by Django 4.1.5 on 2023-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_tempdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=750, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='tempdocument',
            name='file',
            field=models.FileField(max_length=750, upload_to='temp/documents/'),
        ),
    ]
