# Generated by Django 4.1.5 on 2023-03-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reuniones', '0003_alter_document_file_alter_tempdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='creator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='createdReunions', to=settings.AUTH_USER_MODEL),
        ),
    ]
