# Generated by Django 4.1.5 on 2023-04-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0004_reunion_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('callable_roles', models.ManyToManyField(blank=True, related_name='callable_roles', to='reuniones.roles')),
            ],
        ),
    ]
