# Generated by Django 4.1.5 on 2023-04-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0005_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
