# Generated by Django 4.1.5 on 2023-04-02 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0006_rename_roles_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDelegado',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reuniones.role')),
                ('clase', models.CharField(max_length=20)),
            ],
            bases=('reuniones.role',),
        ),
    ]
