# Generated by Django 4.1.5 on 2023-04-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0007_roledelegado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleDelegado',
        ),
    ]
