# Generated by Django 4.1.5 on 2023-04-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0009_remove_role_callable_roles_role_callable_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='callable_roles',
        ),
        migrations.AddField(
            model_name='role',
            name='callable_roles',
            field=models.ManyToManyField(blank=True, to='reuniones.role'),
        ),
    ]
