# Generated by Django 4.0 on 2023-08-17 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reunion_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default=' ')),
                ('date', models.DateField(default='2004-02-01')),
                ('attendees', models.ManyToManyField(related_name='meetings', through='reunion_system.Attendance', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=reunion_system.models.get_file_upload_path)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reunion_system.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='reunion_system.meeting'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='auth.user'),
        ),
    ]
