# Generated by Django 4.0 on 2023-07-14 20:19

from django.db import migrations, models
import django.db.models.deletion
import reunion_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reunion_system.models.get_file_upload_path)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reunion_system.meeting')),
            ],
        ),
    ]
