# Generated by Django 4.1.5 on 2023-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion_system', '0005_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
