# Generated by Django 4.0 on 2023-08-17 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reunion_system', '0005_meeting_date_alter_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
