# Generated by Django 4.0 on 2023-09-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunion_system', '0006_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
    ]
